Bidia/Bidia/Models/BidiaModels/ItemModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Bidia.Models.BidiaModels
{
	public class ItemModel:IModel
	{
		public int Id { get; set; }
		public string Name { get; set; }
		[DataType(DataType.MultilineText)]
		public string ItemDescription { get; set; }
		[DataType(DataType.Text)]
		public string ItemProductType { get; set; }
		[DataType(DataType.Text)]
		public string ItemOriantation { get; set; }
		[DataType(DataType.DateTime)]
		public DateTime ItemDatetime { get; set; }
		[Required]
		public double ItemPrice { get; set; }
		public bool IsHomePage { get; set; }
		public bool IsItemAvailable { get; set; }
		public string DeliveryTime { get; set; }
	}
}

Bidia/Bidia/Controllers/ItemModelsController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bidia.Models.BidiaModels;

namespace Bidia.Controllers
{
	public class ItemModelsController : Controller
	{
		private BidiaDB db = new BidiaDB();

		// GET: ItemModels
		[AllowAnonymous]

		public ActionResult Index(string itemtype)
		{
			var v = db.Items.Where(r => r.ItemProductType == itemtype).OrderByDescending(r => r.ItemDatetime).ToList();
			return View(v);
		}

		// GET: ItemModels/Details/5
		public async Task<ActionResult> Details(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			ItemModel itemModel = await db.Items.FindAsync(id);
			if (itemModel == null)
			{
				return HttpNotFound();
			}
			var Picdirectory = new DirectoryInfo(Server.MapPath("~/Pictures"));
			var fileinfo = Picdirectory.EnumerateFiles();
			var itemfilename = itemModel.Name + ".png";
			var itempic = fileinfo.Where(r => r.Name == itemfilename).ToList();

			var p = "NoImage.png";
			if (itempic.Any())
			{
				var firstOrDefault = itempic.FirstOrDefault();
				if (firstOrDefault != null)
					p = firstOrDefault.Name;
			}

			ViewBag.pic = p;


			return View(itemModel);
		}

		// GET: ItemModels/Create
		[Authorize]
		public ActionResult Create()
		{
			var v = db.ProductTypes.Select(r => r.Name).ToList();
			var x = new List<string> { "No", "Yes" };
			ViewBag.ad = x;
			ViewBag.pro = v;
			return View();
		}

		[Authorize]

		// POST: ItemModels/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Create([Bind(Include = "Id,Name,ItemDescription,ItemProductType,ItemOriantation,ItemDatetime," +
															   "ItemPrice,IsItemAvailable,DeliveryTime,IsHomePage")] ItemModel itemModel,
			HttpPostedFileBase picturefile)
		{
			if (ModelState.IsValid)
			{

				//picture file upload

				if (picturefile != null && picturefile.ContentLength > 0)
				{
					string x1 =itemModel.Name;
					string newfilename = x1 + ".png";
					var filepath = Path.Combine(Server.MapPath("~/Pictures"), newfilename);
					picturefile.SaveAs(filepath);
				}
				db.Items.Add(itemModel);

				await db.SaveChangesAsync();

				var x = db.Items.Where(r => r.ItemProductType == itemModel.ItemProductType).ToList();

				return View("Index", x);
			}

			return View(itemModel);
		}

		// GET: ItemModels/Edit/5
		[Authorize]

		public async Task<ActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			ItemModel itemModel = await db.Items.FindAsync(id);
			if (itemModel == null)
			{
				return HttpNotFound();
			}

			var v = db.ProductTypes.Select(r => r.Name).ToList();
			var x = new List<string> { "No", "Yes" };
			ViewBag.ad = x;
			ViewBag.pro = v;
			return View(itemModel);
		}

		// POST: ItemModels/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[Authorize]

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Edit([Bind(Include = "Id,Name,ItemDescription,ItemProductType,ItemOriantation," +
															 "ItemDatetime,ItemPrice,IsItemAvailable,DeliveryTime,IsHomePage")]
			ItemModel itemModel, HttpPostedFileBase picturefile)
		{
			if (ModelState.IsValid)
			{
				db.Entry(itemModel).State = EntityState.Modified;
				await db.SaveChangesAsync();
				if (picturefile != null && picturefile.ContentLength > 0)
				{
					string x1 = itemModel.Name;
					string newfilename = x1 + ".png";
					var filepath = Path.Combine(Server.MapPath("~/Pictures"), newfilename);
					picturefile.SaveAs(filepath);
				}
				var x =
					db.Items.Where(r => r.ItemProductType == itemModel.ItemProductType).OrderByDescending(r => r.ItemDatetime).ToList();
				return View("Index",x);
			}
			return View(itemModel);
		}

		// GET: ItemModels/Delete/5
		[Authorize]

		public async Task<ActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			ItemModel itemModel = await db.Items.FindAsync(id);
			if (itemModel == null)
			{
				return HttpNotFound();
			}
			return View(itemModel);
		}

		// POST: ItemModels/Delete/5
		[Authorize]

		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> DeleteConfirmed(int id)
		{
			ItemModel itemModel = await db.Items.FindAsync(id);
			db.Items.Remove(itemModel);
			await db.SaveChangesAsync();
			var filepath = Path.Combine(Server.MapPath("~/Pictures"), itemModel.Name);
			var fileInfo=new FileInfo(filepath);

			if (fileInfo!=null)
			{
				fileInfo.Delete();
			}

			var x = db.Items.Where(r => r.ItemProductType == itemModel.ItemProductType).ToList();
			return View("Index",x);
		}


		[AllowAnonymous]
		public PartialViewResult Itempartialview(int id)
		{
			ItemModel itemModel = db.Items.Find(id);
			var Picdirectory = new DirectoryInfo(Server.MapPath("~/Pictures"));
			var fileinfo = Picdirectory.EnumerateFiles();
			var itemfilename = itemModel.Name + ".png";
			var itempic = fileinfo.Where(r => r.Name == itemfilename).ToList();

			var p = "NoImage.png";
			if (itempic.Any())
			{
				var firstOrDefault = itempic.FirstOrDefault();
				if (firstOrDefault != null)
					p = firstOrDefault.Name;
			}

			ViewBag.pic = p;

			return PartialView(itemModel);
		}
		public void paypal_pay(decimal amount, int id)
		{
			var item = db.Items.Find(id);
			decimal d = new decimal();
			d = amount;

			string returnURL = "";
			returnURL += "https://www.paypal.com/xclick/business=KDG32QWYAZ9PY";
			returnURL += "&item_name=" + item.Name;
			returnURL += "&amount=" + d;
			returnURL += "&currency=SEK";
			returnURL += "&return=http://www.paymobd.com/Home/Thank_You";
			returnURL += "&cancel_return=http://www.paymobd.com";
			Response.Redirect(returnURL);
			//return returnURL;

		}
		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				db.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

Bidia/Bidia/Views/ItemModels/Create.cshtml
@model Bidia.Models.BidiaModels.ItemModel


<script src="~/Scripts/jquery-2.2.0.min.js"></script>
<script src="~/Scripts/bootstrap-datepicker.js"></script>
@{
	ViewBag.Title = "Create";
}
<hr />
@using (Html.BeginForm("Create", "ItemModels", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.ItemDescription, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.ItemDescription, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.ItemDescription, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.ItemProductType, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownListFor(m => m.ItemProductType, new SelectList(ViewBag.pro))
				@Html.ValidationMessageFor(model => model.ItemProductType, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.ItemOriantation, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownListFor(m => m.ItemOriantation, new SelectList(ViewBag.ad))
				@Html.ValidationMessageFor(model => model.ItemOriantation, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.ItemDatetime, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.ItemDatetime, new { htmlAttributes = new { @class = "datepicker" } })
				@Html.ValidationMessageFor(model => model.ItemDatetime, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.ItemPrice, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.ItemPrice, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.ItemPrice, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.IsItemAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				<div class="checkbox">
					@Html.CheckBoxFor(model => model.IsItemAvailable)
					@Html.ValidationMessageFor(model => model.IsItemAvailable, "", new { @class = "text-danger" })
				</div>
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.DeliveryTime, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.DeliveryTime, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.DeliveryTime, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.IsHomePage, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				<div class="checkbox">
					@Html.CheckBoxFor(model => model.IsHomePage)
					@Html.ValidationMessageFor(model => model.IsHomePage, "", new { @class = "text-danger" })
				</div>
			</div>
		</div>

		<div class="form-group">
			<a>Picture:</a>
			<div class="col-md-10">
				<div>
					<input type="file" name="picturefile" />
				</div>
			</div>
		</div>



		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Create" class="btn btn-default" />
			</div>
		</div>
	</div>
}


<script type="text/javascript">
	$(".datepicker").datepicker({
		//startDate: '-3y',
		todayHighlight: true
	});
</script>

Bidia/Bidia/Views/ItemModels/Delete.cshtml
@model Bidia.Models.BidiaModels.ItemModel

@{
    ViewBag.Title = "Delete";
}


<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ItemModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemProductType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemProductType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemOriantation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemOriantation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemDatetime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemDatetime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsItemAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsItemAvailable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }
</div>

Bidia/Bidia/Views/ItemModels/Details.cshtml
@model Bidia.Models.BidiaModels.ItemModel

@{
	ViewBag.Title = "Details";
}

<div class="jumbotron customJumbrotron">
	<div class="row">

		<div class="col-md-5" style="text-align: center">
			<img src="~/Pictures/@(ViewBag.pic)" height="400" width="300" />
		</div>
		<div class="col-md-7">

			<p style="line-height: 20px">
				@Model.Name
			</p>
			<table class="table small table-condensed table-responsive table-striped">


				<tr>
					<td>
						<a>Description:</a>
					</td>
					<td>
						@Model.Name
					</td>
				</tr>
				<tr>
					<td>
						<a>Price:</a>
					</td>
					<td>
						@Math.Abs(Model.ItemPrice)
					</td>
				</tr>
				<tr>
					<td>
						<a>Available:</a>
					</td>
					<td>
						@if (Model.IsItemAvailable)
						{
							<a>Available in stock</a>
						}
						else
						{
							<a>Not available in stock</a>
						}
					</td>
				</tr>
				<tr>
					<td>
						<a>Delivery Time:</a>
					</td>
					<td>
						@Model.DeliveryTime
					</td>
				</tr>
			</table>

			<div class="well well-sm  pull-right">
				@Html.ActionLink("Buy Now", "paypal_pay", new { amount = Model.ItemPrice, id = Model.Id }, new { @class = "btn btn-primary pull-right" })
			</div>
		</div>
	</div>
</div>

Bidia/Bidia/Views/ItemModels/Edit.cshtml
@model Bidia.Models.BidiaModels.ItemModel

@{
    ViewBag.Title = "Edit";
}


@using (Html.BeginForm("Edit", "ItemModels", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ItemModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemDescription, "", new { @class = "text-danger" })
            </div>
        </div>

		<div class="form-group">
			@Html.LabelFor(model => model.ItemProductType, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownListFor(m => m.ItemProductType, new SelectList(ViewBag.pro))
				@Html.ValidationMessageFor(model => model.ItemProductType, "", new { @class = "text-danger" })
			</div>
		</div>

        <div class="form-group">
			@Html.LabelFor(model => model.ItemOriantation, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownListFor(m => m.ItemOriantation, new SelectList(ViewBag.ad))
				@Html.ValidationMessageFor(model => model.ItemOriantation, "", new { @class = "text-danger" })
			</div>
		</div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemDatetime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemDatetime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemDatetime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsItemAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsItemAvailable)
                    @Html.ValidationMessageFor(model => model.IsItemAvailable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

	    <div class="form-group">
		    @Html.LabelFor(model => model.DeliveryTime, htmlAttributes: new { @class = "control-label col-md-2" })
		    <div class="col-md-10">
			    @Html.EditorFor(model => model.DeliveryTime, new { htmlAttributes = new { @class = "form-control" } })
			    @Html.ValidationMessageFor(model => model.DeliveryTime, "", new { @class = "text-danger" })
		    </div>
	    </div>
		
	    <div class="form-group">
		    @Html.LabelFor(model => model.IsHomePage, htmlAttributes: new { @class = "control-label col-md-2" })
		    <div class="col-md-10">
			    <div class="checkbox">
				    @Html.CheckBoxFor(model => model.IsHomePage)
				    @Html.ValidationMessageFor(model => model.IsHomePage, "", new { @class = "text-danger" })
			    </div>
		    </div>
	    </div>
		
		<div class="form-group">
			<a>Picture:</a>
			<div class="col-md-10">
				<div>
					<input type="file" name="picturefile" />
				</div>
			</div>
		</div>

	    <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Bidia/Bidia/Views/ItemModels/Index.cshtml
@model System.Collections.Generic.IEnumerable<Bidia.Models.BidiaModels.ItemModel>

@{
	ViewBag.Title = "Index";
}


@section row1
{
	@foreach (var item in Model)
	{
		@Html.Action("Itempartialview", new { id = item.Id });
	}
}

Bidia/Bidia/Views/ItemModels/Itempartialview.cshtml
@using System
@model Bidia.Models.BidiaModels.ItemModel

<div class="jumbotron customJumbrotron">
	<div class="row">

		<div class="col-md-5" style="text-align: center">
			<img src="~/Pictures/@(ViewBag.pic)" height="320" width="240" />
		</div>
		<div class="col-md-7">

			<p style="line-height: 20px">
				@Html.ActionLink(@Model.Name, "Details", new { id = Model.Id }, new { @class = "mark" })
			</p>
			<table class="table small table-condensed table-responsive table-striped">


				<tr>
					<td>
						<a>Description:</a>
					</td>
					<td>
						@Model.Name
					</td>
				</tr>
				<tr>
					<td>
						<a>Price:</a>
					</td>
					<td>
						@Math.Abs(Model.ItemPrice)
					</td>
				</tr>
				<tr>
					<td>
						<a>Available:</a>
					</td>
					<td>
						@if (Model.IsItemAvailable)
						{
							<a>Available in stock</a>
						}
						else
						{
							<a>Not available in stock</a>
						}
					</td>
				</tr>
				<tr>
					<td>
						<a>Delivery Time:</a>
					</td>
					<td>
						@Model.DeliveryTime
					</td>
				</tr>
			</table>

			<div class="well well-sm  pull-right">
				@if (Request.IsAuthenticated)
				{
					@Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary pull-left" })
					@Html.ActionLink("Delete", "Delete", new { id = Model.Id }, new { @class = "btn btn-primary pull-left" })
				}
				@Html.ActionLink("Buy Now", "paypal_pay", new { amount = Model.ItemPrice, id = Model.Id }, new { @class = "btn btn-primary pull-right" })
			</div>
		</div>
	</div>
</div>
<hr>